version: "2"

run:
    timeout: 5m

formatters:
    enable:
        - gofumpt

linters:
    enable:
        - bodyclose        # HTTP body close
        - errcheck         # Unchecked errors
        - gocritic         # Advanced checks
        - gosec            # Security issues
        - govet            # Built-in vet
        - misspell         # Typos in comments/strings
        - nolintlint       # Enforce nolint comments
        - staticcheck      # Go vet++
        - unconvert        # Unnecessary conversions
        - asasalint
        - asciicheck
        - bidichk
        - copyloopvar
        - decorder
        - ineffassign
        - musttag
        - rowserrcheck
        - sqlclosecheck
        - unused
        - whitespace
        - wastedassign
#        - varnamelen
#        - unparam
#        - prealloc
        - noctx
        - nilerr
        - godot
#        - exhaustive
#        - errorlint
#        - contextcheck

    settings:
        gofumpt:
            extra-rules: true
        gocritic:
            disabled-checks:
                - ifElseChain
                - elseif
                - appendAssign
                - assignOp
                - unlambda
        gosec:
            excludes:
                - G104
                - G204
                - G301
                - G302
                - G304
                - G306

issues:
    exclude-rules:
        -   path: _test\.go
            linters:
                - gosec
                - errcheck
        -   path: testutils/*.go
            linters:
                - gosec
                - errcheck

output:
    path-mode: "abs"
    sort-results: true
    formats:
        text:
            colors: true
            path: stdout
            print-issued-lines: true
            print-linter-name: true
    sort-order:
        - linter
        - file
        - severity
