version: "2"

run:
    timeout: 5m

formatters:
    enable:
        - gofumpt

linters:
    enable:
        - asasalint
        - asciicheck
        - bidichk
        - bodyclose        # HTTP body close
        - copyloopvar
        - decorder
        - errcheck         # Unchecked errors
        - errorlint
        - exhaustive
        - gocritic         # Advanced checks
        - godot
        - godox
        - gosec            # Security issues
        - govet            # Built-in vet
        - ineffassign
        - misspell         # Typos in comments/strings
        - musttag
        - nilerr
        - noctx
        - nolintlint       # Enforce nolint comments
        - rowserrcheck
        - sqlclosecheck
        - staticcheck      # Go vet++
        - unconvert        # Unnecessary conversions
        - unparam
        - unused
        - wastedassign
        - whitespace
#        - varnamelen
#        - prealloc
#        - contextcheck

    settings:
        gofumpt:
            extra-rules: true
        gocritic:
            disabled-checks:
                - ifElseChain
                - elseif
                - appendAssign
                - assignOp
                - unlambda
        gosec:
            excludes:
                - G104
                - G204
                - G301
                - G302
                - G304
                - G306

issues:
    exclude-rules:
        -   path: _test\.go
            linters:
                - gosec
                - errcheck
        -   path: testutils/*.go
            linters:
                - gosec
                - errcheck

output:
    path-mode: "abs"
    sort-results: true
    formats:
        text:
            colors: true
            path: stdout
            print-issued-lines: true
            print-linter-name: true
    sort-order:
        - linter
        - file
        - severity
