version: 2

project_name: mehr

snapshot:
  version_template: "nightly"

before:
    hooks:
        - go mod tidy
        - go mod verify

builds:
    -   id: mehr
        binary: mehr
        main: ./cmd/mehr
        env:
            - CGO_ENABLED=0
        goos:
            - linux
            - darwin
        goarch:
            - amd64
            - arm64
        ldflags:
            - -s -w
            - -X github.com/valksor/go-mehrhof/cmd/mehr/commands.Version={{.Version}}
            - -X github.com/valksor/go-mehrhof/cmd/mehr/commands.Commit={{.ShortCommit}}
            - -X github.com/valksor/go-mehrhof/cmd/mehr/commands.BuildTime={{.Date}}

# Binary-only releases (no tarballs)
archives:
    -   format: binary
        name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

checksum:
    name_template: 'checksums.txt'
    algorithm: sha256

# Cosign keyless signing
signs:
    -   cmd: cosign
        signature: "${artifact}.sig"
        certificate: "${artifact}.pem"
        args:
            - sign-blob
            - --yes
            - --output-signature=${signature}
            - --output-certificate=${certificate}
            - ${artifact}
        artifacts: binary

# SBOM generation
sboms:
    -   artifacts: binary
        documents:
            - "sbom.spdx.json"

changelog:
    sort: asc
    filters:
        exclude:
            - '\[skip ci\]'

release:
    # Release already exists (created by nightly.yml or GitHub UI)
    # GoReleaser just uploads artifacts to it
    mode: keep-existing
