package conductor

import (
	"slices"
	"strings"
	"testing"
	"time"

	"github.com/valksor/kvelmo/internal/git"
	"github.com/valksor/kvelmo/internal/storage"
	"github.com/valksor/kvelmo/settings"
)

func TestParseOwnerRepo(t *testing.T) {
	tests := []struct {
		in        string
		wantOwner string
		wantRepo  string
	}{
		{"owner/repo#123", "owner", "repo"},
		{"acme/widgets#1", "acme", "widgets"},
		{"no-hash", "", ""},
		{"onlyowner#5", "", ""},
		{"a/b/c#5", "a", "b/c"},
		{"", "", ""},
	}
	for _, tt := range tests {
		t.Run(tt.in, func(t *testing.T) {
			owner, repo := parseOwnerRepo(tt.in)
			if owner != tt.wantOwner || repo != tt.wantRepo {
				t.Errorf("parseOwnerRepo(%q) = (%q,%q), want (%q,%q)", tt.in, owner, repo, tt.wantOwner, tt.wantRepo)
			}
		})
	}
}

func TestFillPRTemplate(t *testing.T) {
	template := strings.Join([]string{
		"## Summary",
		"",
		"## How to test",
		"",
		"## Related issue",
		"",
	}, "\n")

	out := fillPRTemplate(template, "My change", 3, "https://example.com/issue/1")

	if !strings.Contains(out, "My change") {
		t.Errorf("summary not filled: %q", out)
	}
	if !strings.Contains(out, "3 checkpoint(s) reviewed") {
		t.Errorf("test section not filled: %q", out)
	}
	if !strings.Contains(out, "https://example.com/issue/1") {
		t.Errorf("related section not filled: %q", out)
	}
}

func TestFillPRTemplate_NoSourceURL(t *testing.T) {
	template := "## Related issue\n\n"
	out := fillPRTemplate(template, "desc", 1, "")
	// No source URL → related section is not auto-filled
	if strings.Contains(out, "http") {
		t.Errorf("should not add URL when source is empty: %q", out)
	}
}

func TestBuildPRDescription_FullBody(t *testing.T) {
	fileStatuses := []git.FileStatus{
		{Path: "a.go", Status: "added"},
		{Path: "b.go", Status: "deleted"},
		{Path: "c.go", Status: "modified"},
		{Path: "d.go", Status: "renamed"},
		{Path: "e.go", Status: "weird"},
	}
	prc := &prContext{
		SpecContent:   "the spec content",
		ReviewSummary: "Quality gate: passed",
	}
	body := buildPRDescription("A great feature", 1, 2, "1 file changed", fileStatuses, []settings.PRSection{
		{Title: "Notes", Content: "extra"},
	}, prc)

	for _, want := range []string{
		"## Summary", "A great feature",
		"## Changes", "`+` a.go", "`-` b.go", "`~` c.go", "`>` d.go", "`?` e.go",
		"Diff stats", "## Specification", "the spec content",
		"## Review", "Quality gate: passed",
		"## Checkpoints", "2 checkpoint(s)",
		"## Notes", "extra",
		"Generated by",
	} {
		if !strings.Contains(body, want) {
			t.Errorf("body missing %q\n---\n%s", want, body)
		}
	}
}

func TestBuildPRDescription_NoSpecContentFallback(t *testing.T) {
	body := buildPRDescription("desc", 1, 0, "", nil, nil, &prContext{})
	if !strings.Contains(body, "Implemented according to kvelmo specifications") {
		t.Errorf("expected implementation fallback section, got:\n%s", body)
	}
}

func TestBuildPRDescription_NilContext(t *testing.T) {
	body := buildPRDescription("desc", 0, 0, "", nil, nil, nil)
	if !strings.Contains(body, "## Summary") {
		t.Errorf("expected summary, got:\n%s", body)
	}
	if strings.Contains(body, "## Review") {
		t.Error("should not have review section with nil context")
	}
}

func TestBuildPRDescription_SpecTruncation(t *testing.T) {
	long := strings.Repeat("x", 3000) + "</details>"
	body := buildPRDescription("desc", 1, 0, "", nil, nil, &prContext{SpecContent: long})
	if !strings.Contains(body, "…(truncated)") {
		t.Error("expected truncation marker for long spec")
	}
}

func TestBuildPRDescriptionWithDecisions_NoRecordings(t *testing.T) {
	// With no recordings, ExtractDecisions returns empty and we get the base body.
	body := buildPRDescriptionWithDecisions("desc", 0, 0, "", nil, nil, &prContext{})
	base := buildPRDescription("desc", 0, 0, "", nil, nil, &prContext{})
	if body != base {
		t.Errorf("with no decisions, should equal base body\nbody:\n%s\nbase:\n%s", body, base)
	}
}

func TestBuildReviewSummary_Passed(t *testing.T) {
	passed := true
	got := buildReviewSummary(nil, "", []string{"item1", "item2"}, &passed)
	if !strings.Contains(got, "Quality gate: passed") {
		t.Errorf("missing quality gate passed: %q", got)
	}
	if !strings.Contains(got, "Checklist: 2 item(s) checked") {
		t.Errorf("missing checklist count: %q", got)
	}
}

func TestBuildReviewSummary_Failed(t *testing.T) {
	failed := false
	got := buildReviewSummary(nil, "", nil, &failed)
	if !strings.Contains(got, "Quality gate: failed") {
		t.Errorf("expected failed gate: %q", got)
	}
}

func TestBuildReviewSummary_Empty(t *testing.T) {
	got := buildReviewSummary(nil, "", nil, nil)
	if got != "" {
		t.Errorf("expected empty summary, got %q", got)
	}
}

func TestValidatePRSections(t *testing.T) {
	body := strings.Join([]string{
		"## Summary",
		"Real content here",
		"## Testing",
		"<!-- placeholder -->",
		"## Empty",
		"",
	}, "\n")

	missing := validatePRSections(body, []string{"Summary", "Testing", "Empty", "Absent"})

	has := func(s string) bool {
		return slices.Contains(missing, s)
	}
	if has("Summary") {
		t.Error("Summary has content; should not be reported missing")
	}
	if !has("Testing") {
		t.Error("Testing only has placeholder; should be reported missing")
	}
	if !has("Empty") {
		t.Error("Empty section should be reported missing")
	}
	if !has("Absent") {
		t.Error("Absent header should be reported missing")
	}
}

func TestWorkUnitTaskStateRoundTrip(t *testing.T) {
	created := time.Now().Add(-time.Hour).Round(time.Second)
	updated := time.Now().Round(time.Second)
	approvedAt := time.Now().Add(-30 * time.Minute).Round(time.Second)

	wu := &WorkUnit{
		ID:             "task-1",
		ExternalID:     "ext-1",
		Title:          "Title",
		Description:    "Desc",
		Branch:         "feature/x",
		WorktreePath:   "/tmp/wt",
		Specifications: []string{"spec1.md", "spec2.md"},
		Checkpoints:    []string{"sha1", "sha2"},
		RedoStack:      []string{"sha3"},
		Jobs:           []string{"job1"},
		Metadata:       map[string]string{"k": "v"},
		Tags:           []string{"urgent"},
		Priority:       5,
		HasImplemented: true,
		TaskTraceID:    "trace-1",
		CreatedAt:      created,
		UpdatedAt:      updated,
		Source:         &Source{Provider: "github", Reference: "owner/repo#1", URL: "https://x", Content: "content"},
		Approvals: map[string]ApprovalRecord{
			"submit": {ApprovedBy: "alice", ApprovedAt: approvedAt},
		},
		Hierarchy: &HierarchyContext{
			Parent: &TaskSummary{ID: "p1", Title: "Parent", Description: "pd", URL: "pu", Status: "open"},
			Siblings: []TaskSummary{
				{ID: "s1", Title: "Sib", Description: "sd", URL: "su", Status: "done"},
			},
		},
		CheckpointMeta: map[string]CheckpointMeta{
			"sha1": {Message: "first", State: "planned", CreatedAt: created},
		},
	}
	history := []HistoryEntry{
		{From: StateNone, To: StateLoaded, Event: EventStart, Timestamp: created},
		{From: StateLoaded, To: StatePlanning, Event: EventPlan, Timestamp: updated},
	}

	ts := workUnitToTaskState(StatePlanned, wu, history)
	if ts.State != string(StatePlanned) {
		t.Errorf("State = %q", ts.State)
	}
	if ts.ID != "task-1" || ts.ExternalID != "ext-1" {
		t.Errorf("ids not preserved: %+v", ts)
	}
	if ts.Source == nil || ts.Source.Provider != "github" {
		t.Error("source not converted")
	}
	if ts.Hierarchy == nil || ts.Hierarchy.Parent == nil || ts.Hierarchy.Parent.ID != "p1" {
		t.Error("hierarchy parent not converted")
	}
	if len(ts.Hierarchy.Siblings) != 1 {
		t.Error("hierarchy siblings not converted")
	}
	if len(ts.History) != 2 {
		t.Errorf("history len = %d", len(ts.History))
	}
	if ts.Approvals["submit"].ApprovedBy != "alice" {
		t.Error("approval not converted")
	}
	if ts.CheckpointMeta["sha1"].Message != "first" {
		t.Error("checkpoint meta not converted")
	}

	// Round-trip back
	state, wu2, history2 := taskStateToWorkUnit(ts)
	if state != StatePlanned {
		t.Errorf("round-trip state = %q", state)
	}
	if wu2.ID != wu.ID || wu2.Title != wu.Title || wu2.Branch != wu.Branch {
		t.Errorf("round-trip workunit mismatch: %+v", wu2)
	}
	if !wu2.HasImplemented {
		t.Error("HasImplemented lost in round-trip")
	}
	if wu2.Source == nil || wu2.Source.Reference != "owner/repo#1" {
		t.Error("source lost in round-trip")
	}
	if wu2.Hierarchy == nil || wu2.Hierarchy.Parent == nil || wu2.Hierarchy.Parent.ID != "p1" {
		t.Error("hierarchy lost in round-trip")
	}
	if wu2.Approvals["submit"].ApprovedBy != "alice" {
		t.Error("approval lost in round-trip")
	}
	if wu2.CheckpointMeta["sha1"].State != "planned" {
		t.Error("checkpoint meta lost in round-trip")
	}
	if len(history2) != 2 || history2[0].Event != EventStart {
		t.Errorf("history lost in round-trip: %+v", history2)
	}
}

func TestTaskStateToWorkUnit_NilMaps(t *testing.T) {
	ts := &storage.TaskState{State: string(StateLoaded), ID: "x"}
	state, wu, history := taskStateToWorkUnit(ts)
	if state != StateLoaded {
		t.Errorf("state = %q", state)
	}
	if wu.Metadata == nil {
		t.Error("Metadata should be initialized to non-nil map")
	}
	if len(history) != 0 {
		t.Errorf("history should be empty, got %d", len(history))
	}
}

func TestConvertCheckpointMeta_Empty(t *testing.T) {
	if got := convertCheckpointMetaToStorage(nil); got != nil {
		t.Errorf("nil input should yield nil, got %v", got)
	}
	if got := convertCheckpointMetaFromStorage(nil); got != nil {
		t.Errorf("nil input should yield nil, got %v", got)
	}
}

func TestIsActivePhaseState(t *testing.T) {
	active := []State{StatePlanning, StateImplementing, StateSimplifying, StateOptimizing, StateReviewing}
	for _, s := range active {
		if !isActivePhaseState(s) {
			t.Errorf("isActivePhaseState(%s) = false, want true", s)
		}
	}
	inactive := []State{StateNone, StateLoaded, StatePlanned, StateImplemented, StateSubmitted, StateFailed, StateWaiting, StatePaused, State("garbage")}
	for _, s := range inactive {
		if isActivePhaseState(s) {
			t.Errorf("isActivePhaseState(%s) = true, want false", s)
		}
	}
}
